en/docs/tester/index.html
en/src/tester/index.md

Greg, I don't know if you want to keep the same structure defined in sdxjs. If so, in future PRs I can also add some common (regarding that they appear both in sdxjs and sdxpy) definition terms to the glossary, such as _test runner_, _test subject_, etc., that are missing in sdxpy (but that perfectly fit here). The same applies to the figures. I can help in that front too.

Fix some typos and formatting errors

---

en/src/server/index.md
info/links.yml

I know that this is a WIP but I was curious about the server chapter and couldn't resist the temptation :)
I was also wondering if this sentence:
"Ports 0-1023 are reserved for the operating system's use; anyone else can use the remaining ports."
could be more precise rewriting it as:
"Ports 0-1023 are reserved for common -well-known- TCP/IP applications; it is recommended to use the remaining ports for any other custom application"
Feel free to throw it in /dev/null

Fix typo. Fix 404 in pyfakefs

---

bin/html2tex.py
docs/binary/bit_mask.py
docs/binary/index.html
en/src/binary/bit_mask.py
en/src/binary/index.md
info/head.tex

Add support for correctly typesetting a tilde (not operator in Python) and  >>,>>>,<<,<<< symbols (shift operators in Python) in LaTeX.
Fix a couple of typos.

Binary chapter: Add support for correctly typesetting Python binary operators in LaTeX

---

docs/builder/index.html
en/src/builder/index.md

Apart from the fix, I'm not sure if the Template Method discussion fully applies to this chapter. In sdxjs the **SkeletonBuilder.build** method defined a set of instructions (pattern) to follow  by the child classes:
```
this.loadConfig() 
this.buildGraph() 
this.checkCycles() 
this.run()
```
but in sdxpy the class **ConfigLoader.build** just defines a _build_ method -with a single step _self.load_config_- that has been overriden by its child classes, adding many other methods where the flow of control could be changed. Even though the flow didn't change, there was nothing impeding it.

Fix reference borrowed from sdxjs

---

info/head.tex

This is strange. I don't know why this command in `info/head.tex`:
`\newcommand{\textapprox}{\raisebox{0.5ex}{\texttildelow}}`
was working in my lab's computer (where I have a TeX 2019 version IIRC) but fails with this error: 
`LaTeX Error: Command \textapprox unavailable in encoding T1` in my home's computer (where I have a TeX 2022 version)
```
$ pdflatex -version
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
kpathsea version 6.3.4
````
So I replaced the previous command with this one:
`\DeclareTextCommand{\textapprox}{T1}{\raisebox{0.5ex}{\texttildelow}}`
and now it works like a charm in TeX 2022 but, will it also work in TeX 2021? I'll double check it tomorrow morning.

Fix LaTeX Error: Command \textapprox unavailable in encoding T1

---

docs/matching/index.html
docs/syllabus/index.html
en/src/matching/index.md

"Extract data" makes more sense than "extra data", but it could be the other way around...

Matching patterns: Fix typo

---

en/src/tester/slides/index.html

After changing run_tests to not use a prefix, the call which originally used a prefix needs to be updated.

Remove prefix in run_tests call

---

docs/tester/slides/index.html

add `:` to `if hasattr(func, "skip")`

Fix index.html typo

---

en/src/tester/slides/index.html

The dot notation example uses the string object's title method as a demonstration. This returns the string formatted into title case.
The output on the slides was the word title in title case. Changed to hello.

Fix output of dot notation example.

---

src/archive/backup_oop.py

`python backup_oop.py sample_dir /tmp/backups` does not run due to syntax/logical errors.
Changes:
1. call `super().__init__()` with correct inputs
2. add colon after class `ArchiveLocal(Archive)`
3. use correct variable name `timestamp` --> `t`, `result` --> `results`
4. Add skeleton functions used in successive refinement

fixed syntax errors in backup_oop.py

---

src/glob/test_glob_problem.py

These two tests produce fail even later in the chapter when the class Either is corrected, principally because they miss a `.match("ac")` and a `.match("ax")`, respectively.
```
def test_either_followed_by_literal_match():
assert Either(Lit("a"), Lit("b"), Lit("c"))
def test_either_followed_by_literal_no_match():
assert not Either(Lit("a"), Lit("b"), Lit("x"))
```

Fixes CH4 test missed match call

---

src/interp/index.md

I found the text in the caption inconsistent with the little programming language we are trying to write a parser for. I propose to use the same language in the caption as well.

Make caption consistent with the language

---

src/vm/index.md

In the rest of the chapter, as well as within the actual code and presentation slides, the operation (`op`) code formats are consistently used as `r` for register and `v` for value.
I recognize the potential benefits of introducing additional formats (for instance, format `a` could be used to confirm the validity of an address). However, if these additional formats are not being used in the code, I would suggest standardizing the chapter to exclusively use the `v` format.

/vm - Section 25.1: Make format of `op` codes consistent

---

src/build/build_time.py

BuildBetter class doesn't have "_require". I assume a call to "_must" was intended.

Change "_require" to "_must" in build_time.py

---

src/debugger/vm_break.py

If you try adding a breakpoint and this operation fails (because there is already a breakpoint at that address), the debugger will step to the next instruction, which seems to be unintended behaviour. The same happens for trying to clear a breakpoint at an address where there is no breakpoint. This happens because these two commands return None in case of failure, which interferes with the loop from `interact()` in `vm_extend.py` (the variable `interacting` becomes None, breaking the loop and allowing the VM to step to the next instruction).

Fixed bug in VM debugger for adding/clearing breakpoints

---

src/debugger/vm_base.py

Error message in assert_is_address says "Invalid register" when it should say "Invalid address".

Update error message for assert_is_address in vm_base.py

---

docs/archive/slides/index.html
docs/archive/test_backup.py
src/archive/test_backup.py

(in the end of the section 10.3)
The existing code tests the presence of the manifest many times in the loop, which doesn't seem optimal, so I fixed that.
Also, extracted the timestamp to avoid possible divergency between the mocked and the tested value.

PR for test_nested_example in archive

---

src/viewer/cursor_const.py
src/viewer/size_window.py

The `Window` classes defined in both `src/viewer/size_window.py` and `src/viewer/cursor_const.py` accept user input to determine the size of the drawable area. If no input is given `curses.LINES` and `curses.COLS` are used instead. 
If the user unwittingly provides a size input which is larger than the available area **and** tries to draw into that area, the `curses` raises an error. Example (assuming 15 lines are actually available): 
```
$ python3 cursor_const.py 16 log.txt 20 15
Traceback (most recent call last):
File "/Users/diyartaskiran/*/SDXPY/src/viewer/cursor_const.py", line 36, in <module>
curses.wrapper(lambda stdscr: main(stdscr, size, lines))
File "/Users/diyartaskiran/anaconda3/envs/softwareconstruction/lib/python3.11/curses/__init__.py", line 94, in wrapper
return …
```

/viewer – Fix `Window` size bug 

---

src/index.md

I believe the text located in src/index, under the Chapter 22 outline should read:
"... or in any of dozens of other ways."
It currently reads:
"... or in any of dozens of other days."

fixed typo: day to way

---

src/binary/index.md

- fix typo in the description of hexadecimal notation

Update index.md in /binary section 17.1
